### ISSUE TITLE
NUnit assertion to fluentassertions migration refactorings

### ISSUE THREAD

**Issue by inyutin-maxim** [matkoch/resharper-fluentassertions#5]
Have a good day!
I want to migrate from NUnit assertion to fluentassertions. 
I planned to try to write migration refactorings (as in [doc for migration from MsTest](https://fluentassertions.com/tips/#mstest-migration)) and send you PR.
What do you think about it?

**Comment by matkoch** [comment]
Sure that sounds interesting!

**Comment by mu88** [comment]
@inyutin-maxim I had the same idea in my mind and was super happy when I found that you already did a lot of fundamental work.  
What do you think about the following things:
1. Support for `Assert.Equals()` - how would you implement that? Create another base class similar to `NUnitAssertMigrationServiceBase`? Or can we somehow integrate it into the current code? I'm not sure how to distinguish `Assert.Equals(expectedValue, currentValue)` from `Assert.True(currentValue, "because this is my description")`.
2. I'm mostly working with xUnit which has almost the same assertions like NUnit. Do you see any elegant way of combining these two test frameworks?

Cheers
mu88

**Comment by inyutin-maxim** [comment]
Hi @mu88 Thanks.

1) `Assert.Equals(expectedValue, currentValue)` can be converted to `currentValue.Should().Be(expectedValue[,message][, params object[] parameters])`. I will write today an example of how it should be. I am checking for a specific call from Assert. * and applying codefix for this code.

2) I think that we can extract the base class where we isolate the test framework check, and the logic of checking simple cases by 80% will be identical. But there are difficult situations, for example nUnit contains this way of verifying statements: `Assert.That(currentValue, Is.EqualTo(1))`.  For this type, I plan to select a separate base class that will correct this separate type of checks

**Comment by mu88** [comment]
That sounds good to me! I'm really looking forward to an example

**Comment by inyutin-maxim** [comment]
Hi @mu88 , I have completed my quick fix for `Assert.AreEqual("qwerty", result);` to `result.Should().Be("qwerty")`. you can see my new PR #14

**Comment by matkoch** [comment]
Probably addressed by all the PRs :) Thanks once more!
